### ISSUE TITLE
Support for node.js 20+?

### ISSUE THREAD

**Issue by sammertime** [clhenrick/color-legend-element#34]
Hi there,

Just curious if there are any plans to upgrade this package for use in node.js 20+.  I was using it successfully in an older version of node but came across issues with it once upgrading.

Thanks so much,
S

**Comment by clhenrick** [comment]
@sammertime sorry I didn't have time to get back to you sooner. I haven't tried running node.js with the package, what is the issue you're running into?

**Comment by sammertime** [comment]
@clhenrick no worries at all.  I ended up moving forward with a built in leaflet solution.  The issue I was encountering occurred when I upgraded my node (20) and npm packages.  It complained about the color-legend-element package being on an unsupported version of node js I believe.  I was using parcel to develop locally and wasn't able to perform a code build when including the color-legend-element package.  All the best.

**Comment by clhenrick** [comment]
@sammertime it's probably because I have "engines" in the package.json set to a specific version of node. I think if I change this to allow that version of node and any greater version than it shouldn't throw this error.

However, it looks like this is only enforced when the `engine-strict` config flag is set to `true`, otherwise it will just produce a warning: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

You might try removing that config flag from your `.npmrc` file if you have it set and see if that changes things.

**Comment by clhenrick** [comment]
Reopening for now in case anyone else runs into this issue

**Comment by clhenrick** [comment]
@sammertime I just published a new version (1.0.5), if you have a moment let me know if that fixes your issue. Thanks!
